server:
  port: 8081

spring:
  application:
    name: product-app

eureka:
  instance:
    hostname: localhost
  client:
    service-url:   #  eureka server 的地址， 咱们单实例模式就写自己好了
      defaultZone:  http://localhost:9000/eureka
    register-with-eureka: true
    fetch-registry: true

