server:
  port: 8080

debug: true

spring:
  application:
    name: gateway-app
  cloud:
    nacos:
      discovery:
        serverAddr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
 # 没生效
#          routes:
#          - id: user-app
#            uri: lb://user-app
#            predicates:
#              - path=/user/**
#          - id: product-app
#            uri: lb://product-app
#            predicates:
#              - path=/product/**


