server:
  port: 8080

debug: true

spring:
  application:
    name: gateway-app
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
 # 没生效
#          routes:
#          - id: user-app
#            uri: lb://user-app
#            predicates:
#              - path=/user/**
#          - id: product-app
#            uri: lb://product-app
#            predicates:
#              - path=/product/**


eureka:
  instance:
    hostname: localhost
  client:
    service-url:   #  eureka server 的地址， 咱们单实例模式就写自己好了
      defaultZone:  http://localhost:9000/eureka
    register-with-eureka: true
    fetch-registry: true
