server:
  port: 8082

spring:
  application:
    name: user-app
  cloud:
  nacos:
    discovery:
      serverAddr: 127.0.0.1:8848
    config:
      fileExtension: properties

  zipkin:
    baseUrl: http://localhost:9411


